export const source = {
  // TRN_ID: 'trainId',
  // TRN_Type: 'trainType',
  // TRN_SECT: 'trainSection',
  // TRN_SYM: 'trainSymbol',
  // TRN_DAY: 'trainDay',
  STN_333: [
    'stationSCAC',
    'stationFSAC',
    'station333',
    'stationName',
    'stationCountryCode',
    'stationAbbrevation',
  ],
  STN_ST: [
    'stationSCAC',
    'stationFSAC',
    'station333',
    'stationName',
    'stationCountryCode',
    'stationAbbrevation',
  ],
  // LOCO_INIT: 'locoIdentifier',
  // LOCO_NUMB: 'locoIdentifier',
  // EQP_INIT: 'equipmentIdentifier',
  // EQP_NUMB: 'equipmentIdentifier',
  ARR: 'arrival',
  TRN: 'train',
  STN: 'station',
  TYP: 'type',
  COD: 'code',
};
